### ISSUE TITLE
Train torchreid with veri or vehicle dataset

### ISSUE THREAD

**Issue by irfanfadhullah** [youngjae-avikus/yolov5-deepsort-osnet#1]
Hello, i want to request your help to train a new reid model with vehicle dataset.
Do you know the reference that i can refer to do that? except torchreid official website.
Thank you

**Comment by YoungjaeDev** [comment]
@irfanfadhullah 
hi
First, there are many types of vehicle data set re-id dataset, the most basic is veri-dataset (My guess?). If you search for it, you can receive it after a request from the original owner. Because there are many restrictions on commercial use, it must be used only for research purposes.

After receiving it, I trained with torchreid and put it into the torchreid project by referring to dataset.py below.
https://github.com/youngjae-avikus/vehicle-ReID-baseline/blob/master/vehiclereid/datasets/veri.py

Do you think it helped?

**Comment by irfanfadhullah** [comment]
hi @youngjae-avikus , 
Currently, i followed your instruction and its work.
Thank you for your help.
